### PR TITLE
Fix linking account with email & password on iOS & macOS

### LINKED ISSUE #813: When linking the account with an email address and a password the local state doesn't update
https://github.com/SharezoneApp/sharezone-app/assets/24459435/78a0d7eb-8a25-4792-833e-5ef4c01cb435

The user is created in the backend. It's only a local state issue.

Reproducible with macOS but not with the latest alpah version on Android: 78972fe73cfb35164c57decca54a4308d31146c9

### PR DESCRIPTION
**Pull request by nilsreichardt**
## Description

The issue for #813 was that the `isAnonymous` attribute of the Firebase user has not been updated when linking an anonymous account with email address & password on iOS and macOS. The workaround is to use `reload()` on the Firebase auth user. The bug was caused by #776.

## Working Demo

https://github.com/SharezoneApp/sharezone-app/assets/24459435/c3646063-1179-4584-a789-025f12636c5b

## Related Tickets

Fixes #813

### CODE REVIEW

File: lib/authentification/authentification_base/lib/src/gateways/link_provider_gateway.dart [hunk 1]
```diff
@@ -46,6 +46,13 @@ class LinkProviderGateway extends BlocBase {
         EmailAuthProvider.credential(email: email, password: password);
     await userGateway.linkWithCredential(credential);
 
+    // Even when we are using the `userChanges()` stream, we still need to call
+    // `reload()` because the `isAnonymous` property is not updated on iOS (and
+    // macOS). When the bug is fixed, we can remove this call.
+    //
+    // Bug report: https://github.com/firebase/flutterfire/issues/11520
+    await userGateway.reloadUser();
+
```
Comment (Jonas-Sander) [inline lib/authentification/authentification_base/lib/src/gateways/link_provider_gateway.dart:55]: Couldn't the user be reloaded in the `linkWithCredential` method? In this way the code using the `userGateway` could stay "dumber".

**Review by Jonas-Sander — APPROVED** [review]

File: lib/authentification/authentification_base/lib/src/gateways/link_provider_gateway.dart (hunk 1 above)
Comment (nilsreichardt) [reply lib/authentification/authentification_base/lib/src/gateways/link_provider_gateway.dart]: Yes, that's possible and alos shorter 👍
