### PR TITLE
Fix closing `AppFunctionsDialog` when action completed

### LINKED ISSUE #973: Success sheet sometimes does not close
image

Steps to reproduce:

1. Long press a group
2. Delete group

Logs:
```
flutter: ----------------FIREBASE CRASHLYTICS----------------
flutter: Looking up a deactivated widget's ancestor is unsafe.
At this point the state of the widget's element tree is no longer stable.
To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.
flutter:
#0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure>
framework.dart:4558
#1      Element._debugCheckStateIsActiveForAncestorLookup
framework.dart:4572
#2      Element.findAncestorStateOfType
framework.dart:4643
#3      Navigator.of
navigator.dart:2623
#4      Navigator.pop
navigator.dart:2507
#5      StateDialog.showDialogAutoPop.<anonymous closure>
dialog.dart:39
<asynchronous suspension>
flutter: ----------------------------------------------------
```

### PR DESCRIPTION
**Pull request by nilsreichardt**
The issue was that not the `BuildContext` of the dialog was used. This caused the "Looking up a deactivated widget's ancestor is unsafe." error.

Fixes #973

### CODE REVIEW

File: lib/sharezone_widgets/lib/src/state_sheet/dialog.dart [hunk 1]
```diff
@@ -28,34 +33,47 @@ class StateDialog {
     required Future<bool> future,
     Duration delay = const Duration(milliseconds: 250),
   }) async {
-    final dialogPop = show(context);
+    BuildContext? dialogContext;
+
+    final dialogPop = _show(
+      context,
+      onReceivedContext: (context) => dialogContext = context,
```
Comment (Jonas-Sander) [inline lib/sharezone_widgets/lib/src/state_sheet/dialog.dart:40]:
```suggestion
      onDialogContextCreated: (context) => dialogContext = context,
```

I think all names are confusing because this is kinda hacky, but I personally think that this might a little bit less confusing.

**Review by Jonas-Sander — APPROVED** [review]
