### PR TITLE
Ignore Remote Config errors in integration tests

### LINKED ISSUE #725: Integration tests are failing sometimes because of "[firebase_remote_config/internal] internal remote config fetch error"
```
 [firebase_remote_config/internal] internal remote config fetch error
  package:flutter/src/services/message_codecs.dart 653:7                                                                 StandardMethodCodec.decodeEnvelope
  package:flutter/src/services/platform_channel.dart 315:18                                                              MethodChannel._invokeMethod
  ===== asynchronous gap ===========================
  dart:async                                                                                                             _CustomZone.registerBinaryCallback
  package:remote_configuration/src/implementation/firebase_remote_configuration.dart 66:5                                FirebaseRemoteConfiguration.fetch
  package:sharezone/main/plugin_initializations.dart 87:35                                                               PluginInitializations.initializeRemoteConfiguration
  ===== asynchronous gap ===========================
  dart:async                                                                                                             _CustomZone.registerUnaryCallback
  package:sharezone/main/plugin_initializations.dart 86:5                                                                PluginInitializations.initializeRemoteConfiguration
  package:sharezone/main/plugin_initializations.dart 106:29                                                              runPluginInitializations
  package:sharezone/main/run_app.dart 96:39                                                                              initializeDependencies
  ===== asynchronous gap ===========================
  dart:async                                                                                                             _CustomZone.registerUnaryCallback
  package:sharezone/main/run_app.dart 94:3                                                                               initializeDependencies
  Users/runner/work/sharezone-app/sharezone-app/app/integration_test/app_test.dart 23:26                                 main.<fn>
  ===== asynchronous gap ===========================
  package:stream_channel                                                                                                 _GuaranteeSink.add
  var/folders/cn/nkrr6l5n0jz01kq9jbtb9tg00000gn/T/flutter_tools.nM6Rp2/flutter_test_listener.b7oyG4/listener.dart 53:22  main.<fn>
```

https://github.com/SharezoneApp/sharezone-app/actions/runs/5805989584/job/15738025362

Only happend on Android.

### PR DESCRIPTION
**Pull request by nilsreichardt**
Should fix #725

### CODE REVIEW

File: app/lib/main/plugin_initializations.dart [hunk 1]
```diff
@@ -101,6 +102,25 @@ class PluginInitializations {
...
 
+Future<void> _fetchRemoteConfig(RemoteConfiguration remoteConfiguration) async {
+  try {
+    await remoteConfiguration.fetch();
+  } catch (e) {
+    if (isIntegrationTest && PlatformCheck.isAndroid) {
+      if ('$e'.contains(
+          '[firebase_remote_config/internal] internal remote config fetch error')) {
+        print(
+            "Catched '$e'. Ignoring because we're running an integration test.");
```
Comment (Jonas-Sander) [inline app/lib/main/plugin_initializations.dart:113]:
```suggestion
        log(
            "Catched '$e'. Ignoring because we're running an integration test.");
```

Shouldn't it be this?

**Review by Jonas-Sander — APPROVED** [review]
Hm, I don't really like it, but if it's causing flakes then it's probably necessary.

**Comment by nilsreichardt** [comment]
> Hm, I don't really like it, but if it's causing flakes then it's probably necessary.

I could create a sample app with just Firebase Remote Config and spin up 100 GitHub Actions runner, to test what happens. If have some results, create a FlutterFire issue. But my prediction is that Google just blocks some questions.
