### PR TITLE
Fix opening keyboard when selecting event/exam time

### LINKED ISSUE #1789: Keyboard opens when selecting the time for an event/exam
https://github.com/user-attachments/assets/a8140660-f222-4de9-8efe-20ad2c1dd617

### PR DESCRIPTION
**Pull request by nilsreichardt**
The issue was that the `delayKeyboard()` was calling the `build()` method.

Fixes #1789

### CODE REVIEW

File: app/lib/timetable/timetable_add_event/timetable_add_event_dialog.dart [hunk 1]
```diff
@@ -75,27 +75,39 @@ class TimetableAddEventDialog extends StatelessWidget {
...
   bool hasModifiedData() {
-    return controller!.title.isNotEmpty || controller!.description.isNotEmpty;
+    return controller.title.isNotEmpty || controller.description.isNotEmpty;
   }
 
   @override
   Widget build(BuildContext context) {
-    if (!_hasRequestedTitleFocus) {
-      _hasRequestedTitleFocus = true;
-      delayKeyboard(context: context, focusNode: titleFocusNode);
```
Comment (nilsreichardt) [inline app/lib/timetable/timetable_add_event/timetable_add_event_dialog.dart:90]: @Jonas-Sander Do you know if there was a reason why you called the `delayKeyboard` in the `build()` method instead of using a `StatefulWidget` with `initState`?

Comment (Jonas-Sander) [reply app/lib/timetable/timetable_add_event/timetable_add_event_dialog.dart:90]: No, probably just laziness.

**Review by Jonas-Sander — APPROVED** [review]
