### PR TITLE
Fix changing subject weights

### LINKED ISSUE #1803: Adding a new grade type to weights of a subject will delete the other weights and change final grade type
## Describe the bug

When adding a new grade type (e.g. presentation) to the default weights of a default subject (written exam -> 50%, oral participation -> 50%) then the default weights are deleted and the final grade type of the subject is changed. 

## Steps to reproduce the bug

1. Go to the grades page
2. Tap on the add grade button
3. Select a grade and grade system (e.g. "2+", "1-6 (+-)")
4. Select a subject (e.g. "Deutsch")
5. Create a new term (e.g. "10/2")
6. Select that term
7. Create the grade
8. Tap on the newly created term
9. Tap on the edit icon of the subject
10. At "Berechnung der Fachnote" tap on "Neue Gewichtung hinzufügen"
11. Select a weighting that is not already added, e.g. "Präsentation"
12. Close the subject settings

## Current _broken_ behavior

When opening the subject settings again the 
1. default weightings are gone (written exam -> 50%, oral participation -> 50%) 
2. final grade type has changed (in my example to written exam)

## Expected behavior

1. The default weights should still be there (should they have changed automatically to accomodate the new grade type?).
2. The final grade type should not have changed

## Screenshots, videos or logs

| Phone (v2.2.2) | Web(v2.2.2) |
|--------|--------|
|<video src="https://github.com/user-attachments/assets/16a08d58-17a6-48d1-af5b-6ca1932b5f7d"> | <video src="https://github.com/user-attachments/assets/c89abc20-82ae-4a0b-aa5d-26fa0a17ff62"> | 

## Tested device
- App version: 2.2.2

## Context
Probably applies to a bug report by a user on discord: https://discord.com/channels/545668860859252746/1232365061717102704/1326862647596945419

### PR DESCRIPTION
**Pull request by Jonas-Sander**
Fixes #1803

### CODE REVIEW

**Comment by Jonas-Sander** [comment]
Inside the private grade logic a class called `NonNegativeWeight` is used.
```dart
class NonNegativeWeight extends Weight {
  factory NonNegativeWeight.fromWeight(Weight weight) =>
      NonNegativeWeight.factor(weight.asFactor);
  NonNegativeWeight.factor(num factor) : super.factor(factor) {
    if (factor < 0) {
      throw ArgumentError('Weight must be non-negative');
    }
  }
  NonNegativeWeight.percent(num percent) : super.percent(percent) {
    if (percent < 0) {
      throw ArgumentError('Weight must be non-negative');
    }
  }
}
```

Inside `subject_settings_page_controller.dart` we used the following code:
```dart
  late IMap<GradeTypeId, Weight> _weights;
  // ...
   SubjectSettingsPageController({
      required this.subRef,
      required this.gradesService,
    }) {
    //...
    _weights = _getTerm()!.gradeTypeWeightings;
    //...
  }
```
This threw the following error:
```
  type 'Weight' is not a subtype of type 'NonNegativeWeight' of 'value'
  package:fast_immutable_collections/src/imap/imap.dart 822:27                                       IMap.add
  package:sharezone/grades/pages/subject_settings_page/subject_settings_page_controller.dart 142:25  SubjectSettingsPageController.setGradeWeight
```

This is unexpected for the consuming code of the grades logic.
I need to create a fix so that the consuming code does not break.
Probably it should never see `NonNegativeWeight` - maybe make it a completely different class?

File: app/lib/grades/pages/subject_settings_page/subject_settings_page_controller.dart [hunk 1]
```diff
@@ -31,18 +31,27 @@ class SubjectSettingsPageController extends ChangeNotifier {
...
+      return;
+    }
+
     _subjectName = subject.name;
     final finalGradeType = _getFinalGradeType(subject.finalGradeTypeId);
     _finalGradeTypeDisplayName = _getFinalGradeTypeDisplayName(finalGradeType);
     _finalGradeTypeIcon = _getFinalGradeTypeIcon(finalGradeType);
     _selectableGradeTypes = gradesService.getPossibleGradeTypes();
 
+    // Todo: Explain this workaround
```
Comment (nilsreichardt) [inline app/lib/grades/pages/subject_settings_page/subject_settings_page_controller.dart:46]: Todo is still on purpose in the code?

**Review by nilsreichardt — APPROVED** [review]
Thanks for fixing ❤️  I added the bug back then 😭

File: app/lib/grades/pages/subject_settings_page/subject_settings_page_controller.dart (hunk 1 above)
Comment (Jonas-Sander) [reply app/lib/grades/pages/subject_settings_page/subject_settings_page_controller.dart]: No, thanks for pointing it out!
