### PR TITLE
Fix navigation after signing out

### LINKED ISSUE #117: After signing out and signing in again, the navigation isn't working anymore.
## Describe the bug
If a user signs out, keeps the app open, signs in again, all navigation buttons are not working anymore (nothing happens, if you press the button).

If a user restarts the app, everything is working again.

## Steps to reproduce the bug
1. Sign out
2. Sign in again (doesn’t matter with account)
3. Try to press a button in the button navigation bar, the profile button, or an item in the drawer.

## Current _broken_ behavior
If you tap on a button, which should navigate you to a different page, nothing happens.

## Expected behavior
If you tap on a navigation button, you should be navigated to the expected page.

## Screenshots, videos or logs
https://user-images.githubusercontent.com/24459435/152521005-2fe7ccb7-de04-4222-aaeb-cd4207745f2a.mp4

## Tested device
- Device: iPhone 13
- OS: iOS 15
- App type: iOS
- App version: 1.6.2

## Possible solution
It's something related to the navigation bloc, which is not disposed correctly.

### PR DESCRIPTION
**Pull request by nilsreichardt**
## Description

I just moved the `BlocProvider` for the `navigationBloc` above the `SharezoneApp` so that the `dispose` method of the `NavigationBloc` is not called when signing out.

Resetting the `NavigationBloc` to the overview page is already implemented.

## Related Tickets

Closes #117

### CODE REVIEW

File: app/lib/main/sharezone.dart [hunk 1]
```diff
@@ -93,9 +96,12 @@ class _SharezoneState extends State<Sharezone> with WidgetsBindingObserver {
                     'ALPHA',
                 child: Stack(
                   children: [
-                    BlocProvider(
-                      bloc: signUpBloc,
-                      child: StreamBuilder<AuthUser>(
+                    MultiBlocProvider(
+                      blocProviders: [
+                        BlocProvider<SignUpBloc>(bloc: signUpBloc),
+                        BlocProvider<NavigationBloc>(bloc: navigationBloc),
```
Comment (Jonas-Sander) [inline app/lib/main/sharezone.dart:102]: Please add a comment summarizing why this is here and linking to the issue #117

**Review by Jonas-Sander — APPROVED** [review]
See comment, otherwise LGTM
