### PR TITLE
Fix `loadFeatures` in `FeatureGateway` when `data` is `null`

### LINKED ISSUE #662: Integration tests are failing sometimes because of `Tried calling: []("features")`
```  
  Test: User should be able to load groups
  ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
  The following NoSuchMethodError was thrown running a test:
  The method '[]' was called on null.
  Receiver: null
  Tried calling: []("features")
  
  When the exception was thrown, this was the stack:
  #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
  #1      FeatureGateway.loadFeatures.<anonymous closure> (package:sharezone/account/features/feature_gateway.dart:31:40)
  (elided 35 frames from dart:async and package:stack_trace)
  
  The test description was:
    User should be able to sign in
```

https://github.com/SharezoneApp/sharezone-app/actions/runs/4925325415/jobs/8799422966

### PR DESCRIPTION
**Pull request by nilsreichardt**
Fixes #662

### CODE REVIEW

File: app/lib/account/features/feature_gateway.dart [hunk 1]
```diff
@@ -28,7 +28,7 @@ class FeatureGateway {
       final featureSet = <Feature>{};
 
       final features =
-          Features.fromJson(doc?.data()['features'] as Map<String, dynamic>);
+          Features.fromJson(doc?.get('features') as Map<String, dynamic>);
       if (features != null) {
         if (features.allColors) featureSet.add(AllColors());
```
Comment (nilsreichardt) [inline app/lib/account/features/feature_gateway.dart:33]: Short note: we are not using `AllColors` anymore because since a few years everyone has access to all colors. #664

**Review by Jonas-Sander — APPROVED** [review]
