### PR TITLE
Use native browser viewer for PDF files

### LINKED ISSUE #102: Hyperlinks in PDF document should be clickable.
## Describe the bug
When previewing a PDF inside Sharezone and clicking onto a link inside the document it should open the link inside e.g. a web browser.

## Steps to Reproduce
1. Go to the files page.
2. Open a folder where you can upload a file.
3. Upload a PDF which has a hyperlink (clickable link) inside it.
4. Tap onto the PDF
5. Try to click the link inside the PDF

## Current _broken_ behavior
Nothing happens

## Expected behavior
The URL of hyperlink should be opened inside a browser / new tab / whatever.  
This also expands to e.g. `mailto` URIs (do not work aswell).

## Tested device
 - Device: Pixel 4a / PC
 - OS: Android 12 / Windows 10
 - App version: 1.6.1 (315) / 1.6.2 (316)

## Additional context
This seems to be an issue with the `native_pdf_view` plugin we use.
See: https://github.com/rbcprolabs/packages.flutter/issues/82

### PR DESCRIPTION
**Pull request by nilsreichardt**
https://github.com/SharezoneApp/sharezone-app/assets/24459435/c72d997e-7aea-45b0-a270-b1cee3d8cc18

Using the browser viewer for PDFs brings finally a good experience for the user:

* Great performance
* (Download PDF)
* Search in PDF
* Select text in PDF
* Print PDF
* Jump to pages
* Clickable hyperlinks

Closes #102

### CODE REVIEW

File: lib/filesharing/files_usecases/lib/src/file_viewer/pages/pdf_file_page.dart [hunk 1]
```diff
@@ -38,54 +43,64 @@ class PdfFilePage extends StatelessWidget {
...
+                    return Container();
+                  }
+                }
+
+                if (snapshot.hasError) {
+                  // Catch
+                  return const Center(
+                    child: Text(
+                      'PDF Rendering does not '
+                      'support on the system of this version',
```
Comment (Jonas-Sander) [inline lib/filesharing/files_usecases/lib/src/file_viewer/pages/pdf_file_page.dart:94]: ?

```suggestion
                      'PDF Rendering is not '
                      'supported on this device',
```

**Review by Jonas-Sander — APPROVED** [review]
