### PR TITLE
Fix `permissioned denied` bug when signing out

### LINKED ISSUE #174: `[cloud_firestore/permission-denied] The caller does not have permission to execute the specified operation.` when signing out
## Description
When a user signs out, the console prints a lot of `[cloud_firestore/permission-denied] The caller does not have permission to execute the specified operation.`. This is a problem for writing integration tests because it's now impossible to write a test where you need to log out.

```
flutter:
flutter: Neuer einkommender Link: EinkommenderLink(typ: , zusatzinformationen: {}, einkommensZeitpunkt: EinkommensZeitpunkt.appstart, empty: true)
The Flutter DevTools debugger and profiler on iPhone 13 is available at: http://127.0.0.1:9106?uri=http://127.0.0.1:58192/6BchHN6cHrE=/
flutter: [cloud_firestore/permission-denied] The caller does not have permission to execute the specified operation.
flutter: ----------------FIREBASE CRASHLYTICS----------------
flutter: [cloud_firestore/permission-denied] The caller does not have permission to execute the specified operation.
flutter:
flutter: ----------------------------------------------------
flutter: [cloud_firestore/permission-denied] The caller does not have permission to execute the specified operation.
flutter: ----------------FIREBASE CRASHLYTICS----------------
flutter: [cloud_firestore/permission-denied] The caller does not have permission to execute the specified operation.
flutter:
flutter: ----------------------------------------------------
flutter: [cloud_firestore/permission-denied] The caller does not have permission to execute the specified operation.
flutter: ----------------FIREBASE CRASHLYTICS----------------
flutter: [cloud_firestore/permission-denied] The caller does not have permission to execute the specified operation.
flutter:
flutter: ----------------------------------------------------
flutter: [cloud_firestore/permission-denied] The caller does not have permission to execute the specified operation.
flutter: ----------------FIREBASE CRASHLYTICS----------------
flutter: [cloud_firestore/permission-denied] The caller does not have permission to execute the specified operation.
flutter:
flutter: ----------------------------------------------------
flutter: [cloud_firestore/permission-denied] The caller does not have permission to execute the specified operation.
flutter: ----------------FIREBASE CRASHLYTICS----------------
flutter: [cloud_firestore/permission-denied] The caller does not have permission to execute the specified operation.
flutter:
flutter: ----------------------------------------------------
flutter: [cloud_firestore/permission-denied] The caller does not have permission to execute the specified operation.
flutter: ----------------FIREBASE CRASHLYTICS----------------
flutter: [cloud_firestore/permission-denied] The caller does not have permission to execute the specified operation.
flutter:
flutter: ----------------------------------------------------
flutter: [cloud_firestore/permission-denied] The caller does not have permission to execute the specified operation.
flutter: ----------------FIREBASE CRASHLYTICS----------------
flutter: [cloud_firestore/permission-denied] The caller does not have permission to execute the specified operation.
flutter:
flutter: ----------------------------------------------------
flutter: [cloud_firestore/permission-denied] The caller does not have permission to execute the specified operation.
flutter: ----------------FIREBASE CRASHLYTICS----------------
flutter: [cloud_firestore/permission-denied] The caller does not have permission to execute the specified operation.
flutter:
flutter: ----------------------------------------------------
flutter: [cloud_firestore/permission-denied] The caller does not have permission to execute the specified operation.
flutter: ----------------FIREBASE CRASHLYTICS----------------
flutter: [cloud_firestore/permission-denied] The caller does not have permission to execute the specified operation.
flutter:
flutter: ----------------------------------------------------
flutter: [cloud_firestore/permission-denied] The caller does not have permission to execute the specified operation.
flutter: ----------------FIREBASE CRASHLYTICS----------------
flutter: [cloud_firestore/permission-denied] The caller does not have permission to execute the specified operation.
flutter:
flutter: ----------------------------------------------------
flutter: [cloud_firestore/permission-denied] The caller does not have permission to execute the specified operation.
flutter: ----------------FIREBASE CRASHLYTICS----------------
flutter: [cloud_firestore/permission-denied] The caller does not have permission to execute the specified operation.
flutter:
flutter: ----------------------------------------------------
flutter: [cloud_firestore/permission-denied] The caller does not have permission to execute the specified operation.
flutter: ----------------FIREBASE CRASHLYTICS----------------
flutter: [cloud_firestore/permission-denied] The caller does not have permission to execute the specified operation.
flutter:
flutter: ----------------------------------------------------
```

## Steps to reproduce
1. Sign in
2. Sign out

### PR DESCRIPTION
**Pull request by nilsreichardt**
Finally :) 

**How I fixed the bug:**

To find out which databases the client is trying to access, I used the Firebase Emulator:

1. Run `firebase init` to init the Firebase emulator.
2. Run the firebase emulator: `firebase emulators:start -P sharezone-debug`.
3. Add the following lines to `run_app.dart` after calling `initializeApp()`.

```dart
const emulatorHost = 'localhost
await FirebaseAuth.instance.useAuthEmulator(emulatorHost, 9099)
await FirebaseStorage.instance.useStorageEmulator(emulatorHost, 9199)
FirebaseFirestore.instance.useFirestoreEmulator(emulatorHost, 8080)
```

From there I knew which collection was affected.

**What was the problem?**.

There were several places that were causing the error:

* The `dashboard_bloc' didn't close the subscription.
* `asBroadcastStream()` in `homework_api.dart` and `blackboard_api.dart` caused counting to listen to the stream.
* Multiple `SharezoneGateways` were created in the method to listen to the group join links in `run_app.dart`, but only the last one created was discarded.
* HomeworkGateway wasn't disposed when calling `SharezoneGateway.dispose'.
* SharezoneGateway wasn't disposed of in sharezone.dart.
* JoinedCoursesStream subscription wasn't closed.

However, even with fixes for the described bugs, there was still a ~50% chance that some `permission denied` errors would still be thrown (tested it ~10 times).

Since I had no idea how to fix this, I created a hacky workaround: Create a new stream for auth state changes. When signing out, we tell this stream that the user is signed out, so the widgets are disposed of. 500ms later, we actually sign out the user, hoping that all streams are disposed. Worked for me every time.

This fix should unblock us from writing more integration tests :)

Fix #174

### CODE REVIEW

File: lib/authentification/authentification_base/lib/src/blocs/auth_state_changed.dart [hunk 1]
```diff
@@ -8,6 +8,10 @@
 
 import 'package:authentification_base/src/models/auth_user.dart';
 import 'package:firebase_auth/firebase_auth.dart';
+import 'package:rxdart/rxdart.dart';
+
+final authUserSubject = BehaviorSubject<AuthUser?>.seeded(null);
+Stream<AuthUser?> get authUserStream => authUserSubject.stream;
```
Comment (Jonas-Sander) [inline lib/authentification/authentification_base/lib/src/blocs/auth_state_changed.dart:14]: This wraps the firebase auth stream, correct? Could you add your explanation on why its necessary to wrap it here as well?

**Review by Jonas-Sander — APPROVED** [review]

**Comment by Jonas-Sander** [comment]
🎉🎉 Good job on fixing that :) 🎉🎉
