### PR TITLE
Fixed switch button alignment on `homework_dialog` page

### LINKED ISSUE #1295: Switch buttons are not aligned on the homework dialog page
The homework buttons are not in the vertical position:

image

### PR DESCRIPTION
**Pull request by EvilMonkey09**
I fixed the alignment of the Buttons in the homework_dialog page. The "Privat" button should now be aligned with the other buttons on the page.
Before:
303926743-b22eb08d-dc6e-4775-b45a-7edae719a186

After:
grafik

Closes #1295

## Summary by CodeRabbit

- **Refactor**
	- Updated the homework dialog interface for enhanced user experience.
- **Bug Fixes**
	- Modified the `_SendNotification` class in `homework_dialog.dart` to improve functionality.
	- Updated the `_SendNotificationBase` and `_PrivateHomeworkSwitchBase` classes for better performance.

### CODE REVIEW

File: app/lib/homework/homework_dialog/homework_dialog.dart [hunk 1]
```diff
@@ -959,26 +959,32 @@ class _SendNotification extends StatelessWidget {
...
           onChanged: (newValue) =>
               bloc.add(NotifyCourseMembersChanged(newValue)),
-          sendNotification: state.notifyCourseMembers,
-          description: state.isEditing
-              ? null
-              : "Sende eine Benachrichtigung an deine Kursmitglieder, dass du eine neue Hausaufgabe erstellt hast.",
+          ),
         ),
-      ),
+      )
```
[the remark this answers is not in the document]
Comment (nilsreichardt) [reply app/lib/homework/homework_dialog/homework_dialog.dart:982]: A switch button doesn't have a `tooltip` attribute.

File: app/lib/homework/homework_dialog/homework_dialog.dart [hunk 2]
```diff
@@ -959,26 +959,32 @@ class _SendNotification extends StatelessWidget {
...
+        leading: const Icon(Icons.notifications_active),
+        title: Text(
+          "Kursmitglieder ${state.isEditing ? "über Änderungen " : ""}benachrichtigen",
+        ),
+        subtitle: state.isEditing
+            ? null
+            : const Text(
+                "Kursmitglieder über neue Hausaufgabe benachrichtigen",
+              ),
+        trailing: Switch(
```
Comment (nilsreichardt) [inline app/lib/homework/homework_dialog/homework_dialog.dart:976]: We can use here `Switch.adaptive` instead of `Switch`. `Switch.adaptive` uses the native platform design for the switch button, see https://api.flutter.dev/flutter/material/Switch/Switch.adaptive.html

File: app/lib/homework/homework_dialog/homework_dialog.dart [hunk 3]
```diff
@@ -959,26 +959,32 @@ class _SendNotification extends StatelessWidget {
...
     final bloc = bloc_lib.BlocProvider.of<HomeworkDialogBloc>(context);
-
     return MaxWidthConstraintBox(
       child: SafeArea(
         top: false,
         bottom: false,
-        child: _SendNotificationBase(
-          title:
-              "Kursmitglieder ${state.isEditing ? "über die Änderungen " : ""}benachrichtigen",
+        child: ListTile(
```
Comment (nilsreichardt) [inline app/lib/homework/homework_dialog/homework_dialog.dart:966]: I think it's easier to just replace the `ListTileWithDescription` in the `_SendNotificationBase` widget because now the `HwDialogKeys.notifyCourseMembersTile` key is missing.

```suggestion
        child: _SendNotificationBase(
```

File: app/lib/homework/homework_dialog/homework_dialog.dart [hunk 4]
```diff
@@ -959,26 +959,32 @@ class _SendNotification extends StatelessWidget {
...
+        leading: const Icon(Icons.notifications_active),
+        title: Text(
+          "Kursmitglieder ${state.isEditing ? "über Änderungen " : ""}benachrichtigen",
+        ),
+        subtitle: state.isEditing
+            ? null
+            : const Text(
+                "Kursmitglieder über neue Hausaufgabe benachrichtigen",
```
Comment (nilsreichardt) [inline app/lib/homework/homework_dialog/homework_dialog.dart:974]: @Jonas-Sander What do you think about this shorter text? Having a shorter text makes here sense because it has less space now (because of the `ListTile` widget)

**Review by nilsreichardt — COMMENTED** [review]
Thanks for the PR ❤️ 

I left a few small comments. Also, make sure to format your code with the Dart formatter or using our command in the Sharezone Repo CLI: `sz format`.

File: app/lib/homework/homework_dialog/homework_dialog.dart (hunk 4 above)
Comment (Jonas-Sander) [reply app/lib/homework/homework_dialog/homework_dialog.dart]: I also think it's better like this 👍

**Review by nilsreichardt — APPROVED** [review]
LGTM
